/// <reference types="@cloudflare/workers-types" />
import {describe,it,expect,beforeEach} from 'vitest';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';
import worker from '../worker/index';import {reserve,reserveResearch,cancelUnused,digest,safeURL} from '../worker/env';import {validateClaims,supportedJudgment,type Doc} from '../worker/research';import {CATALOG} from '../src/lib/catalog';import type {Env} from '../worker/env';import {execFileSync} from 'node:child_process';import os from 'node:os';import path from 'node:path';
function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('migrations/0001_initial.sql','utf8'));const wrap=(sql:string,params:unknown[]=[])=>({bind(...p:unknown[]){return wrap(sql,p);},async first(){return sqlite.prepare(sql).get(...params as never[])||null;},async all(){return {results:sqlite.prepare(sql).all(...params as never[])};},async run(){const r=sqlite.prepare(sql).run(...params as never[]);return {meta:{changes:Number(r.changes)}};}});return {sqlite,DB:{prepare:(sql:string)=>wrap(sql),batch:async(statements:{run:()=>Promise<unknown>}[])=>{sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}} as unknown as D1Database};}
let env:Env,sqlite:DatabaseSync;const ctx={waitUntil:()=>{}} as unknown as ExecutionContext;
beforeEach(()=>{const d=database();sqlite=d.sqlite;env={DB:d.DB,DOCUMENTS:{} as R2Bucket,FRONTEND_URL:'https://raydo-max.github.io/stablecoin-risk-radar/',API_URL:'https://example.workers.dev',OWNER_GITHUB_ID:'287957837'};});
describe('backend boundaries',()=>{
 it('public users cannot call any admin operation or paid chat',async()=>{for(const path of ['admin','settings','assets','source','identity','version','research','publish','critical','chat','backup','document']){const r=await worker.fetch(new Request(env.API_URL+'/'+path,{method:['admin','backup','document'].includes(path)?'GET':'POST',body:['admin','backup','document'].includes(path)?undefined:'{}'}),env,ctx);expect(r.status,path).toBe(401);}});
 it('an otherwise valid session for another GitHub ID is denied',async()=>{const token=crypto.randomUUID()+crypto.randomUUID();sqlite.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await digest(token),'123','2099-01-01T00:00:00Z');const r=await worker.fetch(new Request(env.API_URL+'/admin',{headers:{Authorization:'Bearer '+token}}),env,ctx);expect(r.status).toBe(401);});
 it('owner writes require frontend origin and reject invalid budget',async()=>{const token=crypto.randomUUID()+crypto.randomUUID();sqlite.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await digest(token),env.OWNER_GITHUB_ID,'2099-01-01T00:00:00Z');const headers={Authorization:'Bearer '+token,'Content-Type':'application/json'};expect((await worker.fetch(new Request(env.API_URL+'/settings',{method:'POST',headers,body:'{}'}),env,ctx)).status).toBe(403);expect((await worker.fetch(new Request(env.API_URL+'/settings',{method:'POST',headers:{...headers,Origin:'https://raydo-max.github.io'},body:JSON.stringify({profile:'balanced',monthly_budget_usd:-5,automation_enabled:false})}),env,ctx)).status).toBe(400);});
 it('unpublished assets and drafts are absent from public views and history',async()=>{const a=CATALOG[0];sqlite.prepare('INSERT INTO assets VALUES(?,?,0)').run(a.id,JSON.stringify(a));sqlite.prepare('INSERT INTO assessments VALUES(?,?,?,0,?,NULL)').run('draft',a.id,'{}',new Date().toISOString());const p=await (await worker.fetch(new Request(env.API_URL+'/public'),env,ctx)).json() as {assets:unknown[]};expect(p.assets).toEqual([]);const h=await (await worker.fetch(new Request(env.API_URL+'/history?asset='+a.id),env,ctx)).json() as {history:unknown[]};expect(h.history).toEqual([]);});
 it('workflow does not accept unsigned calls',async()=>{expect((await worker.fetch(new Request(env.API_URL+'/workflow',{method:'POST',body:'{}'}),env,ctx)).status).toBe(403);});
 it('atomic reservations enforce $5 across concurrent and repeated attempts',async()=>{const calls=await Promise.allSettled(Array.from({length:20},(_,i)=>reserve(env,'attempt-'+i,'test',.5)));expect(calls.filter(x=>x.status==='fulfilled')).toHaveLength(10);expect(sqlite.prepare('SELECT sum(ceiling_usd) AS total FROM budget_ledger').get()!.total).toBe(5);await reserve(env,'attempt-0','test',.5);expect(sqlite.prepare('SELECT count(*) AS n FROM budget_ledger').get()!.n).toBe(10);});
 it('reserves the whole workflow atomically before dispatch and releases only unused stages',async()=>{await reserve(env,'previous','test',4.6);await expect(reserveResearch(env,'too-large',true)).rejects.toThrow('no workflow dispatched');expect(sqlite.prepare("SELECT count(*) AS n FROM budget_ledger WHERE id LIKE 'too-large-%'").get()!.n).toBe(0);await reserveResearch(env,'fits',false);expect(sqlite.prepare("SELECT count(*) AS n FROM budget_ledger WHERE id LIKE 'fits-%'").get()!.n).toBe(3);await cancelUnused(env,['fits-analysis','fits-jev']);expect(sqlite.prepare("SELECT sum(ceiling_usd) AS n FROM budget_ledger WHERE status!='cancelled'").get()!.n).toBeCloseTo(4.7);});
 it('restores an exported backup into an isolated database, including document search',async()=>{const a=CATALOG[0];sqlite.prepare('INSERT INTO assets VALUES(?,?,1)').run(a.id,JSON.stringify(a));sqlite.prepare('INSERT INTO documents(id,asset_id,url,hash,extracted_hash,title,kind,retrieved_at,body,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run('doc',a.id,a.website,'hash','text-hash','Reserve report','reserve_attestation','2026-10-05','Reserves backed by treasury securities','processed');const token=crypto.randomUUID()+crypto.randomUUID();sqlite.prepare('INSERT INTO sessions VALUES(?,?,?)').run(await digest(token),env.OWNER_GITHUB_ID,'2099-01-01T00:00:00Z');const backup=await (await worker.fetch(new Request(env.API_URL+'/backup',{headers:{Authorization:'Bearer '+token}}),env,ctx)).json();const dir=fs.mkdtempSync(path.join(os.tmpdir(),'radar-restore-test-'));try{const input=path.join(dir,'backup.json'),output=path.join(dir,'restored.sqlite');fs.writeFileSync(input,JSON.stringify(backup));execFileSync(process.execPath,['scripts/restore-local.mjs',input,output],{stdio:'pipe'});const restored=new DatabaseSync(output);try{expect(restored.prepare('SELECT data FROM assets WHERE id=?').get(a.id)!.data).toBe(JSON.stringify(a));expect(restored.prepare("SELECT count(*) AS n FROM document_search WHERE document_search MATCH 'treasury'").get()!.n).toBe(1);expect(restored.prepare('SELECT count(*) AS n FROM sessions').get()!.n).toBe(0);expect(()=>execFileSync(process.execPath,['scripts/restore-local.mjs',input,output],{stdio:'pipe'})).toThrow();}finally{restored.close();}}finally{fs.rmSync(dir,{recursive:true,force:true});}});
 it('rejects malformed semantic probabilities rather than accepting inflated certainty',()=>{for(const noul of [NaN,Infinity,1.1,-1,.89])expect(supportedJudgment({type:'noul',noul})).toBe(false);expect(supportedJudgment({type:'different',noul:1})).toBe(false);expect(supportedJudgment({type:'noul',noul:.9})).toBe(true);});
 it('rejects private/credentialed/non-HTTPS sources',()=>{for(const u of ['http://site.com','https://127.0.0.1','https://user:pass@site.com','https://[::1]','https://host.local','https://site.com:444'])expect(()=>safeURL(u)).toThrow();expect(safeURL('https://www.circle.com/transparency')).toContain('circle.com');});
 it('a quoted reserve attestation cannot satisfy code audit criterion',()=>{const doc:Doc={id:'d',asset_id:'usdt',url:'https://tether.to/',hash:'hash',title:'Reserves',kind:'disclosure',reporting_date:'2026-10-01',retrieved_at:'2026-10-05',body:'Reserve attestations dated 2026-10-01 are not contract audits.',status:'processed'};const result=validateClaims({claims:[{dimension:'technology',criterion:0,met:true,claim:'A current contract code audit exists',quote:doc.body,reporting_quote:doc.body,document_id:'d',kind:'reserve_attestation',reporting_date:'2026-10-01',conflict:false}],explanation:{ru:'x',en:'x'}},CATALOG[0],[doc]);expect(result.claims).toEqual([]);});
});
