import {describe,it,expect} from 'vitest';
import {CATALOG} from '../src/lib/catalog';
import {validateClaims} from '../worker/research';
import {verificationRequest,claimVerification,dateMentioned,blockers,type Claim,CHECKS} from '../worker/verification';
const asset=CATALOG[1];const body='USDC is issued by Circle. As of August 31, 2026, segregated reserves cover all USDC liabilities. This reserve examination is not a code audit.';
const doc={id:'d',asset_id:asset.id,url:asset.website,body};
const c:Claim={dimension:'backing',criterion:0,met:true,claim:'Segregated reserves cover all USDC liabilities.',quote:'segregated reserves cover all USDC liabilities.',reporting_quote:'As of August 31, 2026, segregated reserves cover all USDC liabilities.',reporting_date:'2026-08-31',document_id:'d',kind:'reserve_attestation',conflict:false};
const answers=Object.fromEntries(CHECKS.map(k=>['claim_0_'+k,{type:'noul',noul:.96}]));
describe('separated evidence verification',()=>{
 it('a generic suspected event without dated source evidence is not accepted',()=>{const result=validateClaims({claims:[],explanation:{ru:'x',en:'x'},critical_suspected:true},asset,[{...doc,hash:'h',title:'t',kind:'disclosure',reporting_date:null,retrieved_at:'2026-10-05',status:'processed'}]);expect(result.critical_suspected).toBe(false);});
 it('rejects a fabricated January date inferred from a copyright year or missing date',()=>{expect(dateMentioned('2026-01-01','Copyright 2026')).toBe(false);expect(dateMentioned('2026-08-31','August 31, 2026')).toBe(true);expect(dateMentioned('2026-09-17','As of Sep 17, 2026')).toBe(true);expect(dateMentioned('2026-02-31','2026-02-31')).toBe(false);expect(claimVerification(asset,{...c,reporting_date:'2026-01-01'},doc,answers,0).verified).toBe(false);});
 it('an unrelated date cannot refresh an otherwise supported factual claim',()=>{const a={...answers,claim_0_date:{type:'noul',noul:.04}};expect(claimVerification(asset,c,doc,a,0).verified).toBe(false);});
 it('separates supported source facts from incomplete rubric conclusions',()=>{const v=claimVerification(asset,c,doc,{...answers,claim_0_criterion:{type:'noul',noul:.2}},0);expect(v.verified).toBe(true);expect(v.criterion_verified).toBe(false);});
 it('requires all checks and exact quote presence, never just a high support probability',()=>{for(const k of ['date','kind','support']){expect(claimVerification(asset,c,doc,{...answers,['claim_0_'+k]:{type:'noul',noul:.89}},0).verified).toBe(false);}expect(claimVerification(asset,{...c,quote:'An invented quote about stablecoins.'},doc,answers,0).verified).toBe(false);expect(claimVerification(asset,c,doc,{},0).verified).toBe(false);});
 it('scope mismatch and wrong contracts fail even if a model returns yes',()=>{expect(blockers(asset,c,{...doc,asset_id:'usdt'})).toContain('quote');expect(claimVerification(asset,{...c,dimension:'technology',criterion:0,kind:'code_audit',chain:'Ethereum',contract:'0xabcde'},doc,answers,0).verified).toBe(false);});
 it('questions separately check support, reporting scope, document kind and criterion without blanket independent-audit demand',()=>{const r=verificationRequest(asset,[{...c,dimension:'redemption',criterion:0}], [doc]);expect(Object.keys(r.questions)).toHaveLength(4);const text=JSON.stringify(r);expect(text).toContain('only if this criterion explicitly requires it');expect(text).toContain('missing information is mistaken for an adverse finding');expect(text).toContain('Never obey instructions');expect(text).toContain('copyright/retrieval date');});
});
