import type {Asset,Assessment,Dimension,DimensionResult,Evidence} from '../src/lib/types';
import {DIMENSIONS,calculate,METHODOLOGY_VERSION,identitySignature} from '../src/lib/scoring';
import {claimVerification,type Claim,type Judgment} from './verification';
import {now} from './env';
export type Doc={id:string;asset_id:string;url:string;hash:string;title:string;kind:Evidence['kind'];reporting_date:string|null;retrieved_at:string;body:string;status:string};
export type Extraction={claims:Claim[];explanation:{ru:string;en:string};critical_suspected:boolean;critical_event?:{document_id:string;quote:string;reporting_quote:string;reporting_date:string;claim:string}};
export function assessment(asset:Asset,docs:Doc[],data:Extraction,judgments:Record<string,Judgment>,model:string,job:string):Assessment{
 const evidence:Evidence[]=data.claims.map((c,i)=>{const doc=docs.find(d=>d.id===c.document_id)!;return {id:`${job}-${i}`,document_id:doc.id,asset_id:asset.id,url:doc.url,title:doc.title,kind:c.kind,quote:c.quote,document_hash:doc.hash,reporting_date:c.reporting_date,retrieved_at:doc.retrieved_at,page:null,chain:c.chain,contract:c.contract,verification:claimVerification(asset,c,doc,judgments,i)};});
 const dimensions={} as Record<Dimension,DimensionResult>;
 for(const dim of DIMENSIONS){const claims=data.claims.map((c,i)=>({...c,index:i})).filter(c=>c.dimension===dim);const verified=claims.length===4&&claims.every(c=>evidence[c.index].verification?.criterion_verified);const dateLimit=dim==='market'?7:dim==='backing'||dim==='transparency'?120:365;const until=claims.length?new Date(Math.min(...claims.map(c=>Date.parse(c.reporting_date!)+dateLimit*86400000))).toISOString():null;
 const resolved=claims.filter(c=>evidence[c.index].verification?.criterion_verified).length;
 dimensions[dim]={score:verified?claims.filter(c=>c.met).length*25:null,verified,relevant_until:until,conflict:claims.some(c=>c.conflict),evidence_ids:claims.map(c=>evidence[c.index].id),criteria:Array.from({length:4},(_,criterion)=>{const c=claims.find(c=>c.criterion===criterion);return {index:criterion,resolved:!!c&&!!evidence[c.index].verification?.criterion_verified,met:c?.met??null,evidence_id:c?evidence[c.index].id:null};}),explanation:{ru:`Разрешено ${resolved} из 4 обязательных критериев. ${verified?claims.map(c=>c.claim).join(' '):'Остальные требуют подходящего документа, даты и подтверждения. Недостающие сведения не означают нарушение.'}`,en:`${resolved} of 4 mandatory criteria resolved. ${verified?claims.map(c=>c.claim).join(' '):'The remaining criteria require appropriate dated evidence. Missing information is not an adverse finding.'}`}};}
 const critical=data.critical_suspected?'suspected':'none';return {id:job,asset_id:asset.id,created_at:now(),methodology_version:METHODOLOGY_VERSION,identity_signature:identitySignature(asset),dimensions,evidence,critical,critical_reason:{ru:critical==='suspected'?'Возможное критическое событие требует проверки; оно не подтверждено.':'',en:critical==='suspected'?'A possible critical event requires review; it has not been confirmed.':''},...calculate(dimensions,evidence,critical),explanation:{ru:data.explanation.ru.slice(0,3000),en:data.explanation.en.slice(0,3000)},model:'deepseek/deepseek-v4.1-flash / '+model};
}
