import {owner,startAuth,callback} from './auth';import {settings,now,id,digest,safeURL,type Env} from './env';
import {updateMarket} from './market';import {launch,workflow} from './research';import {chat} from './chat';
import {publicAssessment,assessmentForAsset,identitySignature,METHODOLOGY_VERSION,REFRESH_HOURS,isDue,DIMENSIONS} from '../src/lib/scoring';import type {Asset,Assessment,Settings,Profile} from '../src/lib/types';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}});
export async function publishedAssets(env:Env){const rows=await env.DB.prepare(`SELECT a.data,(SELECT data FROM assessments WHERE asset_id=a.id AND published=1 ORDER BY created_at DESC LIMIT 1) AS assessment FROM assets a WHERE visible=1`).all<{data:string;assessment:string|null}>();return rows.results.map(r=>({...JSON.parse(r.data),assessment:r.assessment?assessmentForAsset(JSON.parse(r.assessment),JSON.parse(r.data)):null})) as Asset[];}
async function adminData(env:Env){const s=await settings(env);const jobs=await env.DB.prepare('SELECT id,asset_id,kind,status,stage,error,created_at,updated_at FROM jobs ORDER BY created_at DESC LIMIT 40').all();const reviews=await env.DB.prepare('SELECT id,asset_id,data FROM assessments WHERE published=0 AND reviewed_at IS NULL ORDER BY created_at DESC LIMIT 30').all<{id:string;asset_id:string;data:string}>();const verificationRows=await env.DB.prepare('SELECT assessment_id,data,verification FROM facts WHERE assessment_id IN(SELECT id FROM assessments WHERE published=0 AND reviewed_at IS NULL ORDER BY created_at DESC LIMIT 30)').all<{assessment_id:string;data:string;verification:string}>();const reviewVerification=new Map(verificationRows.results.map(row=>{const fact=JSON.parse(row.data),v=JSON.parse(row.verification);const confidence=typeof v.judgment?.noul==='number'&&Number.isFinite(v.judgment.noul)&&v.judgment.noul>=0&&v.judgment.noul<=1?v.judgment.noul:null;return [fact.id,{confidence,verified:v.judgment?.type==='noul'&&confidence!==null&&confidence>=.9,claim:v.claim?.claim||'',criterion:(v.claim?.dimension||'')+':'+v.claim?.criterion}];}));const spend=await env.DB.prepare("SELECT COALESCE(sum(CASE WHEN status='settled' THEN COALESCE(actual_usd,ceiling_usd) ELSE 0 END),0) AS spent,COALESCE(sum(CASE WHEN status='reserved' THEN ceiling_usd ELSE 0 END),0) AS reserved,COALESCE(sum(CASE WHEN status!='cancelled' THEN ceiling_usd ELSE 0 END),0) AS allocated FROM budget_ledger WHERE month=?").bind(now().slice(0,7)).first();const discoveries=await env.DB.prepare("SELECT * FROM events WHERE kind='source_discovery' ORDER BY created_at DESC LIMIT 15").all();const all=await env.DB.prepare("SELECT data,(SELECT data FROM assessments WHERE asset_id=assets.id AND published=1 ORDER BY created_at DESC LIMIT 1) AS assessment FROM assets").all<{data:string;assessment:string|null}>();return {assets:all.results.map(r=>({...JSON.parse(r.data),assessment:r.assessment?assessmentForAsset(JSON.parse(r.assessment),JSON.parse(r.data)):null})),settings:s,jobs:jobs.results,reviews:reviews.results.map(r=>({id:r.id,asset_id:r.asset_id,assessment:(()=>{const a=publicAssessment(JSON.parse(r.data));a.evidence=a.evidence.map(e=>({...e,verification:reviewVerification.get(e.id)||e.verification}));return a;})()})),...spend,discoveries:discoveries.results,configuration:{oauth:!!env.GITHUB_CLIENT_ID&&!!env.GITHUB_CLIENT_SECRET,tavily:!!env.TAVILY_API_KEY,openrouter:!!env.OPENROUTER_API_KEY,jev:!!env.TYPESAFE_API_KEY,qstash:!!env.QSTASH_TOKEN},next_checks:Object.fromEntries(Object.entries(REFRESH_HOURS[s.profile as Profile]).map(([k,h])=>[k,s[`last_${k==='documents'?'documents':k}_at`]?new Date(Date.parse(s[`last_${k}_at`])+h*3600000).toISOString():null]))};}
async function route(request:Request,env:Env,ctx:ExecutionContext){
 const u=new URL(request.url);const path=u.pathname.replace(/^\//,'');
 if(path==='workflow'){if(request.method!=='POST'||!env.QSTASH_CURRENT_SIGNING_KEY||!env.QSTASH_NEXT_SIGNING_KEY||!request.headers.has('Upstash-Signature'))return json({error:'Signed QStash request required'},403);return workflow(env).fetch(request,env as unknown as Record<string,string|undefined>);}
 if(request.method==='GET'&&path==='auth/github')return startAuth(env);
 if(request.method==='GET'&&path==='auth/callback')return callback(request,env);
 if(request.method==='GET'&&path==='health')return json({status:'ok',methodology:'1.0-experimental',backend:'Cloudflare Workers + D1 + R2',auth_configured:!!env.GITHUB_CLIENT_ID&&!!env.GITHUB_CLIENT_SECRET,research_configured:!!env.TAVILY_API_KEY&&!!env.OPENROUTER_API_KEY&&!!env.TYPESAFE_API_KEY&&!!env.QSTASH_TOKEN});
 if(request.method==='GET'&&path==='public')return json({assets:await publishedAssets(env)});
 if(request.method==='GET'&&path==='history'){const rows=await env.DB.prepare('SELECT data FROM assessments WHERE asset_id=? AND published=1 ORDER BY created_at DESC LIMIT 50').bind(u.searchParams.get('asset')||'').all<{data:string}>();return json({history:rows.results.map(r=>JSON.parse(r.data))});}
 if(!await owner(request,env))return json({error:'Owner access required'},401);
 if(request.method==='GET'&&path==='session')return json({owner:true});
 if(request.method==='GET'&&path==='admin')return json(await adminData(env));
 if(request.method==='GET'&&path==='document'){const d=await env.DB.prepare('SELECT raw_key FROM documents WHERE id=?').bind(u.searchParams.get('id')).first<{raw_key:string}>();const object=d?.raw_key?await env.DOCUMENTS.get(d.raw_key):null;if(!object)return json({error:'Document unavailable'},404);return new Response(object.body,{headers:{'Content-Type':'application/octet-stream','Content-Disposition':'attachment; filename="document"','Cache-Control':'no-store'}});}
 if(request.method==='GET'&&path==='backup'){const tables=['assets','settings','assessments','documents','facts','jobs','budget_ledger','events'];const data:Record<string,unknown>={schema_version:1,created_at:now()};for(const table of tables)data[table]=(await env.DB.prepare(`SELECT * FROM ${table}`).all()).results;return json(data);}
 if(request.method!=='POST')return json({error:'Not found'},404);
 if(request.headers.get('Origin')!==new URL(env.FRONTEND_URL).origin&&request.headers.get('Origin')!=='http://127.0.0.1:5173')return json({error:'Invalid request origin'},403);
 if(Number(request.headers.get('Content-Length')||0)>15000)return json({error:'Request too large'},413);const raw=await request.text();if(raw.length>15000)return json({error:'Request too large'},413);let b:Record<string,unknown>;try{b=JSON.parse(raw);}catch{return json({error:'Invalid JSON'},400);}
 if(path==='logout'){await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(request.headers.get('Authorization')!.slice(7))).run();return json({ok:true});}
 if(path==='settings'){if(!['economy','balanced','intensive'].includes(String(b.profile))||typeof b.monthly_budget_usd!=='number'||!Number.isFinite(b.monthly_budget_usd)||b.monthly_budget_usd<0||b.monthly_budget_usd>100||typeof b.automation_enabled!=='boolean')return json({error:'Invalid settings'},400);if(b.automation_enabled&&(!env.TAVILY_API_KEY||!env.OPENROUTER_API_KEY||!env.TYPESAFE_API_KEY||!env.QSTASH_TOKEN))return json({error:'Configure all research credentials before enabling paid automation'},409);await env.DB.prepare("UPDATE settings SET data=json_set(data,'$.profile',?,'$.monthly_budget_usd',?,'$.automation_enabled',json(?)) WHERE id=1").bind(b.profile,b.monthly_budget_usd,JSON.stringify(b.automation_enabled)).run();return json({ok:true});}
 if(path==='assets'){if(typeof b.symbol!=='string'||!/^[-A-Za-z0-9]{1,15}$/.test(b.symbol)||typeof b.name!=='string'||b.name.length<2||b.name.length>100)return json({error:'Invalid identity'},400);const website=safeURL(b.website);const asset:Asset={id:b.symbol.toLowerCase()+'-'+id().slice(0,8),symbol:b.symbol,name:b.name,issuer:b.name,website,source_urls:[website],mechanism:'unknown',color:'#611f69',description:{ru:'Идентичность и тип обеспечения требуют проверки.',en:'Identity and collateral mechanism require review.'},versions:[],market_cap:null,price:null,market_checked_at:null,assessment:null};await env.DB.prepare('INSERT INTO assets VALUES(?,?,0)').bind(asset.id,JSON.stringify(asset)).run();return json({asset},201);}
 if(path==='source'||path==='identity'||path==='version'){const row=await env.DB.prepare('SELECT data FROM assets WHERE id=?').bind(String(b.asset_id||'')).first<{data:string}>();if(!row)return json({error:'Asset not found'},404);const a=JSON.parse(row.data) as Asset;
  if(path==='source'){const source=safeURL(b.url);if(b.remove===true)a.source_urls=a.source_urls.filter(url=>url!==source);else{if(a.source_urls.length>=5&&!a.source_urls.includes(source))return json({error:'Maximum 5 approved URLs per research batch'},400);a.source_urls=[...new Set([...a.source_urls,source])];}}
  if(path==='identity'){if(!['fiat','crypto','synthetic'].includes(String(b.mechanism))||typeof b.issuer!=='string'||b.issuer.length>100)return json({error:'Invalid asset identity'},400);a.issuer=b.issuer;a.mechanism=b.mechanism as Asset['mechanism'];}
  if(path==='version'){if(typeof b.chain!=='string'||b.chain.length>60||typeof b.contract!=='string'||b.contract.length<5||b.contract.length>120||typeof b.bridged!=='boolean')return json({error:'Invalid contract version'},400);safeURL(b.source);a.versions=a.versions.filter(v=>v.chain!==b.chain||v.contract!==b.contract);a.versions.push({chain:b.chain,contract:b.contract,status:'unassessed',bridged:b.bridged});}
  await env.DB.batch([env.DB.prepare('UPDATE assets SET data=? WHERE id=?').bind(JSON.stringify(a),a.id),env.DB.prepare('INSERT INTO events VALUES(?,?,?,?,?)').bind(id(),a.id,'owner_'+path,JSON.stringify(b),now())]);return json({ok:true});}
 if(path==='research'){const found=await env.DB.prepare('SELECT id FROM assets WHERE id=?').bind(String(b.asset_id||'')).first();if(!found)return json({error:'Asset not found'},404);return json({job_id:await launch(env,String(b.asset_id),b.extended===true)},202);}
 if(path==='publish'||path==='reject'){const row=await env.DB.prepare('SELECT data,asset_id FROM assessments WHERE id=? AND published=0').bind(String(b.assessment_id||'')).first<{data:string;asset_id:string}>();if(!row)return json({error:'Review not found'},404);const at=now();if(path==='reject'){await env.DB.prepare('UPDATE assessments SET reviewed_at=? WHERE id=?').bind(at,b.assessment_id).run();return json({ok:true});}
  const a=publicAssessment(JSON.parse(row.data));const asset=await env.DB.prepare('SELECT data FROM assets WHERE id=?').bind(row.asset_id).first<{data:string}>();if(a.methodology_version!==METHODOLOGY_VERSION)return json({error:'Methodology changed; rerun research before publishing'},409);if(a.identity_signature!==identitySignature(JSON.parse(asset!.data)))return json({error:'Asset identity changed; rerun research before publishing'},409);if(JSON.parse(asset!.data).mechanism==='unknown')return json({error:'Confirm issuer and mechanism before publication'},409);a.reviewed_at=at;await env.DB.batch([env.DB.prepare('UPDATE assessments SET data=?,published=1,reviewed_at=? WHERE id=?').bind(JSON.stringify(a),at,b.assessment_id),env.DB.prepare('UPDATE assets SET visible=1 WHERE id=?').bind(row.asset_id)]);return json({ok:true});}
 if(path==='critical'){const evidence_id=String(b.evidence_id||'');const found=await env.DB.prepare('SELECT f.id FROM facts f JOIN assessments a ON a.id=f.assessment_id WHERE f.id=? AND a.asset_id=(SELECT asset_id FROM assessments WHERE id=?)').bind(evidence_id,String(b.assessment_id||'')).first();if(!found)return json({error:'Documented evidence required'},400);if(typeof b.reason!=='string'||b.reason.length<20||b.reason.length>1500)return json({error:'Detailed reason required'},400);const row=await env.DB.prepare('SELECT data,asset_id FROM assessments WHERE id=? AND published=1').bind(String(b.assessment_id||'')).first<{data:string;asset_id:string}>();if(!row)return json({error:'Publication not found'},404);const a=JSON.parse(row.data) as Assessment;const next=publicAssessment({...a,id:id(),created_at:now(),critical:'confirmed',critical_reason:{ru:b.reason,en:b.reason}});await env.DB.prepare('INSERT INTO assessments VALUES(?,?,?,1,?,?)').bind(next.id,row.asset_id,JSON.stringify(next),next.created_at,now()).run();return json({ok:true});}
 if(path==='chat'){if(typeof b.question!=='string'||b.question.length<3||b.question.length>1000||!['ru','en'].includes(String(b.lang)))return json({error:'Invalid question'},400);return json(await chat(env,b.question,String(b.lang)));}
 return json({error:'Not found'},404);
}
export async function scheduled(env:Env){
 const s=await settings(env) as Settings & {last_dispatch_at?:string};const cadence=REFRESH_HOURS[s.profile];if(isDue(s.last_market_at,cadence.market)){try{await updateMarket(env);}catch{await env.DB.prepare("INSERT INTO jobs(id,kind,status,stage,error,created_at,updated_at) VALUES(?,'market','failed','fetch','Market source unavailable; previous data retained',?,?)").bind(id(),now(),now()).run();}}
 await env.DB.batch([env.DB.prepare('DELETE FROM sessions WHERE expires_at<?').bind(now()),env.DB.prepare('DELETE FROM oauth_states WHERE expires_at<?').bind(now())]);
 if(!s.automation_enabled||s.monthly_budget_usd<=0)return;
 if(!isDue(s.last_dispatch_at||null,Math.min(cadence.documents,4)))return;const extended=isDue(s.last_search_at,cadence.search);if(!extended&&!isDue(s.last_documents_at,cadence.documents))return;
 const rows=await env.DB.prepare('SELECT id FROM assets WHERE visible=1').all<{id:string}>();for(const a of rows.results){try{await launch(env,a.id,extended);}catch{break;}}
 await env.DB.prepare("UPDATE settings SET data=json_set(data,'$.last_dispatch_at',?) WHERE id=1").bind(now()).run();
}
export default {async fetch(request:Request,env:Env,ctx:ExecutionContext){let response:Response;try{if(request.method==='OPTIONS')response=new Response(null,{status:204});else response=await route(request,env,ctx);}catch(e){const message=e instanceof Error?e.message:'Request failed';response=json({error:/budget|credentials|HTTPS|URL|Workflow dispatch|Invalid/.test(message)?message:'Operation failed; previous publication retained'},400);}
 const headers=new Headers(response.headers);const origin=request.headers.get('Origin');if(origin===new URL(env.FRONTEND_URL).origin||origin==='http://127.0.0.1:5173'){headers.set('Access-Control-Allow-Origin',origin);headers.set('Vary','Origin');headers.set('Access-Control-Allow-Headers','Authorization,Content-Type');headers.set('Access-Control-Allow-Methods','GET,POST,OPTIONS');}return new Response(response.body,{status:response.status,headers});},async scheduled(_event:ScheduledEvent,env:Env,ctx:ExecutionContext){ctx.waitUntil(scheduled(env));}};
