import type {Dimension,Mechanism,Evidence} from '../src/lib/types';
export const CRITERIA:Record<Dimension,string[]>={
 backing:['Evidence demonstrates assets cover liabilities including an explicit reserve or collateral shortfall assessment.','Collateral composition, valuation and concentration are documented.','Custody, segregation and legal claim to collateral are documented.','Collateral-specific stress controls (liquidations, haircuts or hedge margins) are independently evidenced.'],
 redemption:['Eligible redeemers and legal redemption rights are documented.','Fees, minimum amounts, settlement time and restrictions are disclosed.','Mechanism for redemption at the dollar target is evidenced.','Redemption under stress and suspension conditions are documented and tested or independently reviewed.'],
 technology:['An independent code audit corresponds to a currently identified chain and contract version.','Mint, freeze and upgrade authorities and their safeguards are evidenced.','Critical oracle, liquidation or settlement dependencies have independently reviewed controls.','Open audit findings, remediation and incident response controls are evidenced.'],
 governance:['Issuer or protocol controllers and accountable governance are identified.','Material bank, custodian, exchange and other counterparties are disclosed.','Key management, access control and change approval protections are evidenced.','Failure, insolvency and recovery arrangements are independently evidenced.'],
 market:['Observed peg history, observation period and material deviations are documented.','Exit liquidity is measured with depth or slippage data, not market capitalization alone.','Venue concentration and exit paths under stress are evidenced.','Material historical depegs and recoveries are reviewed using independent data.'],
 transparency:['Reserve or collateral assurance is independently issued with its scope disclosed.','Assurance reporting period and limitations are identified.','Public reporting cadence and material changes are documented.','Independent financial audit, reserve attestation and code audit scopes are explicitly distinguished.']};
export const ALLOWED_KINDS:Record<Dimension,Evidence['kind'][]>={backing:['reserve_attestation','financial_audit','disclosure'],redemption:['terms','disclosure','financial_audit'],technology:['code_audit','disclosure'],governance:['terms','financial_audit','disclosure','code_audit'],market:['market'],transparency:['reserve_attestation','financial_audit','code_audit','disclosure']};
export function rubric(mechanism:Mechanism){return {version:'1.0-experimental',mechanism,criteria:CRITERIA,collateral_guidance:mechanism==='fiat'?'Evaluate fiat reserves, liquidity, custody and legal redemption.':mechanism==='synthetic'?'Evaluate collateral, exchange margin, hedging, funding rates, custodian and exchange insolvency.':mechanism==='crypto'?'Evaluate actual collateral mix including real world assets, liquidation, oracle and governance risks.':'Mechanism unverified: do not infer collateral type or publish an aggregate.'};}
